export const INTERESTS = [
    'snowboarding',
    'post modern art',
    'comic books',
    'vinyl toys',
    'software',
    'foodie',
    'nature',
    'travelling',
    'hiking',
    'gym',
    'sushi',
    'scary movies',
    'punk music',
]
